steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaJarLocation: 'c:/mta.jar'
  neoDeploy:
    neoHome: 'C:/neo'
    neo:
      credentialsId: 'CM'
      account: p2001269540trial
      host: hanatrial.ondemand.com
