steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaJarLocation: 'c:/mta.jar'
  neoDeploy:
    neoHome: 'C:/neo-java-web-sdk-3.9.9'
    neo:
      credentialsId: 'CM'
      account: 'P2001269540'
      host: 'hana.ondemand.com'
