#Steps Specific Configuration
general:
  changeManagement:
    endpoint: 'https://vhcals4hci:50000/sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV'
    credentialsId: 'CM'
    type: 'SOLMAN'
steps:
  mtaBuild:
    buildTarget: 'NEO'
  transportRequestCreate:
    developmentSystemId: '000'
  transportRequestUploadFile:
    applicationId: 'HCP'
